Redesign
Cyber4All/security-injections-3.0 pull request #14
Opened 2020-01-14 16:24 UTC by EVogel1999

This is a UI redesign of security injections.  The aim of this is to make the modules more modern and fitting with the current cyber4all team.  This design makes the module more modifiable, UI speaking, allowing for more, or less, sections then the standard 6.
![image](https://user-images.githubusercontent.com/32078831/72361888-304a0700-36c0-11ea-948a-3d9f3928a074.png)
Mobile View:
![image](https://user-images.githubusercontent.com/32078831/72361975-58d20100-36c0-11ea-900c-68731e7090e4.png)
![image](https://user-images.githubusercontent.com/32078831/72362015-6c7d6780-36c0-11ea-8655-4239015e242d.png)

2020-01-14 18:18 UTC, pzalep1 requested changes

2020-01-14 18:18 UTC, pzalep1 commented on resources/template.html
> +				<img alt="Feedback" src="http://cis1.towson.edu/~cssecinj/wp-content/uploads//feedback9.png">
alt="Submit Feedback"

2020-01-14 18:18 UTC, pzalep1 commented on resources/template.html
> -											<!--NEED SOMETHING HERE-->
Should be a message for browsers that don't support javascript

2020-01-14 18:18 UTC, pzalep1 commented on resources/template.html
> +									<a class="btn btn-info btn-md" id="si-certificate-link"
Should be a button. Links go to new pages, buttons perform actions on pages

2020-01-14 18:18 UTC, pzalep1 commented on resources/template.html
> -							<button type="submit" class="btn btn-primary" ng-disabled="submitButtonDisabled">Submit</button>
aria-label

2020-01-14 18:18 UTC, pzalep1 commented on resources/template.html
> +								<a
Link needs aria-label

2020-01-16 18:57 UTC, pzalep1 commented on resources/template.html
> +			<a class="feedback" data-toggle="modal" data-target="#fbModal">
Why is the link here twice?

2020-01-17 14:39 UTC, EVogel1999 commented on resources/template.html
> +			<a class="feedback" data-toggle="modal" data-target="#fbModal">
No idea.  I just removed it.

2020-01-21 19:00 UTC, merged