Chore/sc 18513/instructions to create a security injection
Cyber4All/security-injections-3.0 pull request #36
Opened 2023-04-18 20:37 UTC by shanioffe

Made some updates to the new security injections READMEs, just some links and additional details. No major changes.

2023-04-21 15:39 UTC, bereketsega requested changes
Looks good, just small changes.

2023-04-21 15:39 UTC, bereketsega commented on How to create a Security Injection.md
> +```java
```suggestion
```javascript
```

2023-04-21 15:39 UTC, bereketsega commented on content/Secure Coding/Input Validation/CS0 Pseudocode/checklist.js
> +>>>>>>> Stashed changes
```suggestion
			$("#"+question).prop('checked', true);	// check off question

			// take focus away from current question
			$("#"+question+"-label").removeClass("si-checklist-active");
			$("#" + question + "-progress-label").addClass("progress-hidden");
			$("#" + question + "-progress-label").removeClass("progress");
```

2023-04-21 15:39 UTC, bereketsega commented on content/Secure Coding/Input Validation/CS0 Pseudocode/checklist.js
> +>>>>>>> Stashed changes
```suggestion
					// highlights correct answer before moving on to next question
					setTimeout(function(){
						previousWaitingOnCount += waitingOn.length;
						current = advance(current);
					}, 500);
					previousWaitingOnCount += waitingOn.length;
					// console.log("before advance function");
					current = advance(current);
```

2023-04-21 15:39 UTC, bereketsega commented on resources/angular.js
> +>>>>>>> Stashed changes
```suggestion
```

2023-04-21 15:39 UTC, bereketsega commented on create.js
> +>>>>>>> Stashed changes
```suggestion
```

2023-04-21 15:39 UTC, bereketsega commented on create.js
> +=======
```suggestion
```

2023-04-21 15:39 UTC, bereketsega commented on content/Secure Coding/Input Validation/CS0 Pseudocode/checklist.js
> +>>>>>>> Stashed changes
```suggestion
	// helps reset prog bar for each question
	let previousWaitingOnCount = 0;
```

2023-04-24 15:18 UTC, Cwagne17 reviewed
After the merge comment lines are removed, looks good.

2023-04-24 19:08 UTC, Maliyaa approved these changes
Great! Just remove the merge lines 😄

2023-04-25 14:25 UTC, JosueMolinaMorales reviewed
Just the changes already mentioned

2023-04-25 14:48 UTC, jouypo23 reviewed
Looks good, just remove the changes requested above.

2023-04-26 18:41 UTC, bereketsega approved these changes

2023-04-27 15:18 UTC, JosueMolinaMorales approved these changes

2023-04-27 20:01 UTC, jouypo23 approved these changes

2023-04-28 13:59 UTC, merged